/**
 * Englify — English learning site.
 * Exercises are generated by an AI provider (config.aiProvider):
 *  - 'pollinations' (default) — free keyless API, no registration;
 *  - 'claude' — Claude Code CLI (`claude -p`) via the owner's subscription.
 */
const express = require('express');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const CONFIG_PATH = path.join(__dirname, 'config.json');
const DEFAULT_CONFIG = {
  port: 3000,
  // Google OAuth client ID (Web application). Empty => dev login enabled.
  googleClientId: '',
  // DonationAlerts app credentials (https://www.donationalerts.com/application/clients)
  daClientId: '',
  daClientSecret: '',
  daRedirectUri: 'http://localhost:3000/api/da/callback',
  // Public donation page, e.g. https://www.donationalerts.com/r/yourname
  daDonateUrl: '',
  premiumPriceRub: 199,
  premiumDays: 30,
  freeDailyLimit: 15,
  adminEmails: [],
  // 'auto' (default) — try Ollama, then Pollinations; or force one of:
  // 'ollama' — local AI, free and unlimited; 'pollinations' — free keyless API;
  // 'claude' — Claude Code CLI via the owner's subscription
  aiProvider: 'auto',
  ollamaUrl: 'http://localhost:11434',
  ollamaModel: 'qwen2.5:3b',
  claudeModel: 'sonnet'
};
let config = { ...DEFAULT_CONFIG };
if (fs.existsSync(CONFIG_PATH)) {
  try {
    config = { ...DEFAULT_CONFIG, ...JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')) };
  } catch (e) {
    console.error('config.json is invalid JSON, using defaults:', e.message);
  }
}

// ---------------------------------------------------------------------------
// Tiny JSON-file database
// ---------------------------------------------------------------------------
const DATA_DIR = path.join(__dirname, 'data');
const DB_PATH = path.join(DATA_DIR, 'db.json');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

let db = {
  secret: crypto.randomBytes(32).toString('hex'),
  users: {},            // id -> user
  pool: {},             // level -> type -> [exercise]
  processedDonations: [],
  daTokens: null        // { access, refresh, expiresAt }
};
if (fs.existsSync(DB_PATH)) {
  try { db = { ...db, ...JSON.parse(fs.readFileSync(DB_PATH, 'utf8')) }; }
  catch (e) { console.error('db.json corrupted, starting fresh:', e.message); }
}
let saveTimer = null;
function saveDb() {
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));
  }, 300);
}

// ---------------------------------------------------------------------------
// Sessions (signed cookie)
// ---------------------------------------------------------------------------
function sign(value) {
  return crypto.createHmac('sha256', db.secret).update(value).digest('base64url');
}
function makeSession(userId) {
  return userId + '.' + sign(userId);
}
function parseSession(cookieHeader) {
  if (!cookieHeader) return null;
  const m = /(?:^|;\s*)englify_session=([^;]+)/.exec(cookieHeader);
  if (!m) return null;
  const [userId, sig] = decodeURIComponent(m[1]).split('.');
  if (!userId || !sig) return null;
  try {
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(sign(userId)))) return null;
  } catch { return null; }
  return db.users[userId] || null;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function newPayCode() {
  return 'EN-' + crypto.randomBytes(3).toString('hex').toUpperCase();
}

function upsertUser({ googleSub, email, name, picture }) {
  let user = Object.values(db.users).find(u => (googleSub && u.googleSub === googleSub) || (email && u.email === email));
  if (!user) {
    user = {
      id: crypto.randomUUID(),
      googleSub: googleSub || null,
      email: email || null,
      name: name || 'Ученик',
      picture: picture || null,
      createdAt: Date.now(),
      xp: 0,
      done: 0,
      correct: 0,
      streak: 0,
      lastActiveDay: null,
      level: 'A2',
      payCode: newPayCode(),
      premiumUntil: 0,
      usage: { date: today(), count: 0 }
    };
    db.users[user.id] = user;
  } else {
    if (name) user.name = name;
    if (picture) user.picture = picture;
    if (googleSub) user.googleSub = googleSub;
  }
  saveDb();
  return user;
}

function isPremium(user) {
  return user.premiumUntil > Date.now();
}
function isAdmin(user) {
  if (user.dev) return true;
  return !!user.email && config.adminEmails.map(e => e.toLowerCase()).includes(user.email.toLowerCase());
}
function publicUser(user) {
  return {
    id: user.id, name: user.name, email: user.email, picture: user.picture,
    xp: user.xp, done: user.done, correct: user.correct, streak: user.streak,
    level: user.level, payCode: user.payCode,
    premium: isPremium(user), premiumUntil: user.premiumUntil,
    admin: isAdmin(user),
    usedToday: user.usage.date === today() ? user.usage.count : 0,
    dailyLimit: config.freeDailyLimit
  };
}

// ---------------------------------------------------------------------------
// AI providers
// ---------------------------------------------------------------------------

// Pollinations — free text generation API, no key and no registration.
async function callPollinations(prompt, timeoutMs = 120000) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch('https://text.pollinations.ai/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: ctrl.signal,
      body: JSON.stringify({
        messages: [{ role: 'user', content: prompt }],
        model: 'openai',
        // random seed — otherwise Pollinations returns a cached identical answer
        seed: Math.floor(Math.random() * 1e9),
        private: true
      })
    });
    if (!res.ok) throw new Error('Pollinations HTTP ' + res.status + ': ' + (await res.text()).slice(0, 200));
    return (await res.text()).trim();
  } finally {
    clearTimeout(timer);
  }
}

// Claude Code CLI — uses the owner's Claude subscription, no API key.
function callClaude(prompt, timeoutMs = 180000) {
  return new Promise((resolve, reject) => {
    // `claude -p` reads the prompt from stdin; stdin avoids Windows quoting issues.
    const child = spawn('claude', ['-p', '--model', config.claudeModel], {
      shell: true,
      windowsHide: true,
      env: { ...process.env, CLAUDE_CODE_ENTRYPOINT: undefined, CLAUDECODE: undefined }
    });
    let out = '', err = '';
    const timer = setTimeout(() => { child.kill(); reject(new Error('claude CLI timeout')); }, timeoutMs);
    child.stdout.on('data', d => out += d);
    child.stderr.on('data', d => err += d);
    child.on('error', e => { clearTimeout(timer); reject(e); });
    child.on('close', code => {
      clearTimeout(timer);
      if (code === 0) resolve(out.trim());
      else reject(new Error('claude CLI exited ' + code + ': ' + err.slice(0, 500)));
    });
    child.stdin.write(prompt);
    child.stdin.end();
  });
}

// Ollama — local AI server, free and unlimited (https://ollama.com).
async function callOllama(prompt, timeoutMs = 300000) {
  const res = await fetch(config.ollamaUrl + '/api/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    signal: AbortSignal.timeout(timeoutMs),
    body: JSON.stringify({
      model: config.ollamaModel,
      prompt,
      stream: false,
      options: { temperature: 0.9 }
    })
  });
  if (!res.ok) throw new Error('Ollama HTTP ' + res.status + ': ' + (await res.text()).slice(0, 200));
  const data = await res.json();
  return String(data.response || '').trim();
}

async function ollamaAvailable() {
  try {
    const res = await fetch(config.ollamaUrl + '/api/tags', { signal: AbortSignal.timeout(2000) });
    if (!res.ok) return false;
    const { models = [] } = await res.json();
    return models.some(m => m.name.startsWith(config.ollamaModel.split(':')[0]));
  } catch { return false; }
}

async function callAI(prompt, timeoutMs) {
  switch (config.aiProvider) {
    case 'claude': return callClaude(prompt, timeoutMs);
    case 'ollama': return callOllama(prompt, timeoutMs);
    case 'pollinations': return callPollinations(prompt, timeoutMs);
    default: { // 'auto': local Ollama first, then the free web API
      if (await ollamaAvailable()) return callOllama(prompt, timeoutMs);
      return callPollinations(prompt, timeoutMs);
    }
  }
}

function extractJson(text) {
  const start = text.indexOf('[');
  const end = text.lastIndexOf(']');
  if (start !== -1 && end > start) {
    try { return JSON.parse(text.slice(start, end + 1)); } catch { /* try object form below */ }
  }
  // Some models wrap the array in an object: {"exercises":[...]}
  const oStart = text.indexOf('{');
  const oEnd = text.lastIndexOf('}');
  if (oStart !== -1 && oEnd > oStart) {
    const obj = JSON.parse(text.slice(oStart, oEnd + 1));
    const arr = Object.values(obj).find(Array.isArray);
    if (arr) return arr;
    return [obj]; // single exercise / verdict object
  }
  throw new Error('no JSON in response');
}

const TYPES = ['mchoice', 'gap', 'translate', 'order', 'listen'];
const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1'];

const TYPE_SPECS = {
  mchoice: `{"type":"mchoice","question":"<grammar or vocabulary question in Russian or an English sentence with a choice>","options":["...","...","...","..."],"correct":<index 0-3>,"explanation":"<short explanation in Russian>"}`,
  gap: `{"type":"gap","sentence":"<English sentence with ___ for the missing word>","answer":"<the missing word>","translation":"<Russian translation of the full sentence>","explanation":"<short explanation in Russian>"}`,
  translate: `{"type":"translate","ru":"<sentence in Russian>","answers":["<best English translation>","<acceptable variant>","<acceptable variant>"],"hint":"<one key word or grammar hint in Russian>"}`,
  order: `{"type":"order","words":["<shuffled","words","of","sentence>"],"answer":"<the correct English sentence>","ru":"<Russian translation>"}`,
  listen: `{"type":"listen","text":"<English sentence to be read aloud, 5-12 words>","ru":"<Russian translation>"}`
};

const TOPICS = [
  'daily life', 'travel', 'work and office', 'food and cooking', 'technology', 'nature and weather',
  'sports', 'music and movies', 'shopping', 'health', 'family and friends', 'school and studying',
  'hobbies', 'transport', 'animals', 'holidays', 'money', 'clothes and fashion', 'city life', 'emotions'
];
function pickTopics(n) {
  const shuffled = [...TOPICS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

function buildPrompt(level, type, n) {
  return `You are an English exercise generator for Russian-speaking students.
Generate exactly ${n} exercises of type "${type}" for CEFR level ${level}.
Use these topics: ${pickTopics(3).join(', ')} (variation seed: ${crypto.randomBytes(4).toString('hex')}).
Every exercise must be about a different sentence — no two exercises may share the same sentence or answer.
Vary grammar points appropriate for ${level}.
Return ONLY a JSON array, no markdown, no commentary. Each element must match this schema exactly:
${TYPE_SPECS[type]}
Rules:
- All explanations, hints and translations must be in Russian.
- English content difficulty must match CEFR ${level}.
- For "order": 5-9 words, shuffled, no duplicates of the correct order.
- For "gap": exactly one blank written as ___.
- For "translate": 2-4 accepted answer variants, first is the most natural.
- Output must be valid JSON.`;
}

// Content fingerprint used to keep already-seen exercises out of rotation.
function exHash(ex) {
  const key = [ex.type, ex.question, ex.sentence, ex.ru, ex.text, ex.answer, (ex.answers || [])[0]]
    .filter(Boolean).join('|').toLowerCase().replace(/\s+/g, ' ');
  return crypto.createHash('sha1').update(key).digest('hex').slice(0, 12);
}
function rememberServed(user, hash) {
  user.recent = user.recent || [];
  user.recent.push(hash);
  if (user.recent.length > 50) user.recent.splice(0, user.recent.length - 50);
  db.servedHashes = db.servedHashes || [];
  if (!db.servedHashes.includes(hash)) {
    db.servedHashes.push(hash);
    if (db.servedHashes.length > 500) db.servedHashes.splice(0, db.servedHashes.length - 500);
  }
}

const inFlight = new Set();
async function refillPool(level, type) {
  const key = level + ':' + type;
  if (inFlight.has(key)) return;
  inFlight.add(key);
  try {
    const raw = await callAI(buildPrompt(level, type, 6));
    db.pool[level] = db.pool[level] || {};
    const pool = db.pool[level][type] = db.pool[level][type] || [];
    const known = new Set(pool.map(exHash).concat(db.servedHashes || []));
    const items = extractJson(raw).filter(it => it && it.type === type && !known.has(exHash(it)));
    if (!items.length) throw new Error('empty batch (all duplicates?)');
    pool.push(...items);
    saveDb();
    console.log(`[pool] +${items.length} ${type}/${level} (now ${pool.length})`);
  } catch (e) {
    console.error(`[pool] refill ${key} failed:`, e.message);
  } finally {
    inFlight.delete(key);
  }
}

// Built-in fallback exercises so the site works even while Claude is generating.
const FALLBACK = {
  mchoice: [
    { type: 'mchoice', question: 'She ___ to work every day.', options: ['go', 'goes', 'going', 'gone'], correct: 1, explanation: 'Present Simple, 3-е лицо ед. числа — добавляем -es.' },
    { type: 'mchoice', question: 'Выберите перевод слова «приложение» (программа):', options: ['appliance', 'application', 'applause', 'apply'], correct: 1, explanation: 'Application — приложение (программа).' },
    { type: 'mchoice', question: 'I have lived here ___ 2015.', options: ['for', 'since', 'from', 'during'], correct: 1, explanation: 'Since + точка во времени, for + период.' },
    { type: 'mchoice', question: 'They ___ football when it started to rain.', options: ['played', 'were playing', 'have played', 'play'], correct: 1, explanation: 'Past Continuous — длительное действие, прерванное другим событием.' },
    { type: 'mchoice', question: 'Выберите перевод слова «расписание»:', options: ['schedule', 'scale', 'scheme', 'screen'], correct: 0, explanation: 'Schedule — расписание, график.' },
    { type: 'mchoice', question: 'This is ___ interesting book I have ever read.', options: ['more', 'most', 'the most', 'much'], correct: 2, explanation: 'Превосходная степень: the most + прилагательное.' },
    { type: 'mchoice', question: 'If it ___ tomorrow, we will stay at home.', options: ['rains', 'will rain', 'rained', 'rain'], correct: 0, explanation: 'First Conditional: if + Present Simple, will + инфинитив.' },
    { type: 'mchoice', question: 'Выберите перевод слова «улучшать»:', options: ['improve', 'implore', 'import', 'impress'], correct: 0, explanation: 'Improve — улучшать(ся).' }
  ],
  gap: [
    { type: 'gap', sentence: 'There ___ a lot of people at the party yesterday.', answer: 'were', translation: 'Вчера на вечеринке было много людей.', explanation: 'People — множественное число, прошедшее время: were.' },
    { type: 'gap', sentence: 'I am interested ___ learning English.', answer: 'in', translation: 'Я заинтересован в изучении английского.', explanation: 'Interested in — устойчивое сочетание.' },
    { type: 'gap', sentence: 'She has been working here ___ five years.', answer: 'for', translation: 'Она работает здесь пять лет.', explanation: 'For + период времени (five years).' },
    { type: 'gap', sentence: 'We are looking forward ___ seeing you.', answer: 'to', translation: 'Мы с нетерпением ждём встречи с вами.', explanation: 'Look forward to + герундий.' },
    { type: 'gap', sentence: 'He ___ up early every morning.', answer: 'gets', translation: 'Он встаёт рано каждое утро.', explanation: 'Get up — вставать; 3-е лицо: gets.' },
    { type: 'gap', sentence: 'I have never ___ to Japan.', answer: 'been', translation: 'Я никогда не был в Японии.', explanation: 'Present Perfect: have been to — бывать где-то.' },
    { type: 'gap', sentence: 'Turn ___ the lights, please. It is too dark.', answer: 'on', translation: 'Включи свет, пожалуйста. Слишком темно.', explanation: 'Turn on — включать; turn off — выключать.' }
  ],
  translate: [
    { type: 'translate', ru: 'Я учу английский каждый день.', answers: ['I learn English every day.', 'I study English every day.'], hint: 'Present Simple' },
    { type: 'translate', ru: 'Сколько это стоит?', answers: ['How much is it?', 'How much does it cost?'], hint: 'вопрос о цене' },
    { type: 'translate', ru: 'Где ближайшая станция метро?', answers: ['Where is the nearest metro station?', 'Where is the nearest subway station?'], hint: 'nearest — ближайший' },
    { type: 'translate', ru: 'Мне нравится путешествовать с друзьями.', answers: ['I like travelling with friends.', 'I like to travel with friends.', 'I enjoy travelling with friends.'], hint: 'like + -ing / to' },
    { type: 'translate', ru: 'Вчера я посмотрел интересный фильм.', answers: ['Yesterday I watched an interesting film.', 'I watched an interesting movie yesterday.'], hint: 'Past Simple' },
    { type: 'translate', ru: 'Можно мне чашку кофе, пожалуйста?', answers: ['Can I have a cup of coffee, please?', 'Could I have a cup of coffee, please?'], hint: 'вежливая просьба' }
  ],
  order: [
    { type: 'order', words: ['coffee', 'like', 'I', 'morning', 'in', 'the'], answer: 'I like coffee in the morning', ru: 'Я люблю кофе по утрам.' },
    { type: 'order', words: ['is', 'name', 'my', 'Anna'], answer: 'My name is Anna', ru: 'Меня зовут Анна.' },
    { type: 'order', words: ['to', 'we', 'cinema', 'the', 'went', 'yesterday'], answer: 'We went to the cinema yesterday', ru: 'Вчера мы ходили в кино.' },
    { type: 'order', words: ['you', 'do', 'time', 'what', 'up', 'get'], answer: 'What time do you get up', ru: 'Во сколько ты встаёшь?' },
    { type: 'order', words: ['never', 'she', 'meat', 'eats'], answer: 'She never eats meat', ru: 'Она никогда не ест мясо.' },
    { type: 'order', words: ['raining', 'it', 'now', 'is'], answer: 'It is raining now', ru: 'Сейчас идёт дождь.' }
  ],
  listen: [
    { type: 'listen', text: 'The weather is really nice today.', ru: 'Сегодня действительно хорошая погода.' },
    { type: 'listen', text: 'Could you help me with this task?', ru: 'Не могли бы вы помочь мне с этой задачей?' },
    { type: 'listen', text: 'I usually have breakfast at eight.', ru: 'Я обычно завтракаю в восемь.' },
    { type: 'listen', text: 'My brother works in a big company.', ru: 'Мой брат работает в большой компании.' },
    { type: 'listen', text: 'Let us meet near the park entrance.', ru: 'Давай встретимся у входа в парк.' },
    { type: 'listen', text: 'She bought a new phone last week.', ru: 'Она купила новый телефон на прошлой неделе.' }
  ]
};

// ---------------------------------------------------------------------------
// DonationAlerts
// ---------------------------------------------------------------------------
const DA_BASE = 'https://www.donationalerts.com';

async function daRefreshIfNeeded() {
  const t = db.daTokens;
  if (!t) return null;
  if (t.expiresAt && t.expiresAt - Date.now() < 60000 && t.refresh) {
    try {
      const res = await fetch(DA_BASE + '/oauth/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          grant_type: 'refresh_token',
          refresh_token: t.refresh,
          client_id: config.daClientId,
          client_secret: config.daClientSecret,
          scope: 'oauth-user-show oauth-donation-index'
        })
      });
      const data = await res.json();
      if (data.access_token) {
        db.daTokens = {
          access: data.access_token,
          refresh: data.refresh_token || t.refresh,
          expiresAt: Date.now() + (data.expires_in || 3600) * 1000
        };
        saveDb();
      }
    } catch (e) { console.error('[DA] token refresh failed:', e.message); }
  }
  return db.daTokens && db.daTokens.access;
}

async function daPollDonations() {
  const access = await daRefreshIfNeeded();
  if (!access) return { checked: false, reason: 'DonationAlerts не подключен' };
  try {
    const res = await fetch(DA_BASE + '/api/v1/alerts/donations?page=1', {
      headers: { Authorization: 'Bearer ' + access }
    });
    if (!res.ok) return { checked: false, reason: 'DA API: HTTP ' + res.status };
    const { data = [] } = await res.json();
    let activated = 0;
    for (const d of data) {
      if (db.processedDonations.includes(d.id)) continue;
      const msg = String(d.message || '').toUpperCase();
      const user = Object.values(db.users).find(u => u.payCode && msg.includes(u.payCode.toUpperCase()));
      if (!user) continue;
      const amountOk = d.currency !== 'RUB' || Number(d.amount) >= config.premiumPriceRub;
      if (!amountOk) continue;
      db.processedDonations.push(d.id);
      const base = Math.max(user.premiumUntil, Date.now());
      user.premiumUntil = base + config.premiumDays * 24 * 3600 * 1000;
      activated++;
      console.log(`[DA] premium activated for ${user.email || user.name} until ${new Date(user.premiumUntil).toISOString()}`);
    }
    if (activated) saveDb();
    return { checked: true, activated };
  } catch (e) {
    return { checked: false, reason: e.message };
  }
}
setInterval(() => { if (db.daTokens) daPollDonations(); }, 90000);

// ---------------------------------------------------------------------------
// HTTP API
// ---------------------------------------------------------------------------
const app = express();
app.use(express.json({ limit: '100kb' }));
app.use(express.static(path.join(__dirname, 'public')));

function auth(req, res, next) {
  const user = parseSession(req.headers.cookie);
  if (!user) return res.status(401).json({ error: 'Не авторизован' });
  req.user = user;
  next();
}
function setSessionCookie(res, userId) {
  res.setHeader('Set-Cookie',
    `englify_session=${encodeURIComponent(makeSession(userId))}; HttpOnly; Path=/; Max-Age=${180 * 24 * 3600}; SameSite=Lax`);
}

app.get('/api/config', (req, res) => {
  res.json({
    googleClientId: config.googleClientId,
    devLogin: !config.googleClientId,
    premiumPriceRub: config.premiumPriceRub,
    premiumDays: config.premiumDays,
    donateUrl: config.daDonateUrl,
    daConnected: !!db.daTokens,
    levels: LEVELS,
    types: TYPES
  });
});

// --- Auth ---
app.post('/api/auth/google', async (req, res) => {
  const { credential } = req.body || {};
  if (!credential) return res.status(400).json({ error: 'Нет токена' });
  if (!config.googleClientId) return res.status(400).json({ error: 'Google Client ID не настроен' });
  try {
    const r = await fetch('https://oauth2.googleapis.com/tokeninfo?id_token=' + encodeURIComponent(credential));
    const info = await r.json();
    if (!r.ok || info.aud !== config.googleClientId) {
      return res.status(401).json({ error: 'Токен Google не прошёл проверку' });
    }
    const user = upsertUser({ googleSub: info.sub, email: info.email, name: info.name, picture: info.picture });
    setSessionCookie(res, user.id);
    res.json({ user: publicUser(user) });
  } catch (e) {
    res.status(500).json({ error: 'Ошибка проверки токена: ' + e.message });
  }
});

// Dev login — only available while Google client ID is not configured.
app.post('/api/auth/dev', (req, res) => {
  if (config.googleClientId) return res.status(403).json({ error: 'Отключено: настроен вход через Google' });
  const name = (req.body && String(req.body.name || '').trim()) || 'Тестовый ученик';
  const user = upsertUser({ email: 'dev@localhost', name });
  user.dev = true;
  saveDb();
  setSessionCookie(res, user.id);
  res.json({ user: publicUser(user) });
});

app.post('/api/logout', (req, res) => {
  res.setHeader('Set-Cookie', 'englify_session=; HttpOnly; Path=/; Max-Age=0');
  res.json({ ok: true });
});

app.get('/api/me', auth, (req, res) => res.json({ user: publicUser(req.user) }));

app.post('/api/level', auth, (req, res) => {
  const level = String((req.body || {}).level || '');
  if (!LEVELS.includes(level)) return res.status(400).json({ error: 'Неверный уровень' });
  req.user.level = level;
  saveDb();
  res.json({ user: publicUser(req.user) });
});

// --- Exercises ---
app.get('/api/exercise', auth, (req, res) => {
  const user = req.user;
  const level = LEVELS.includes(req.query.level) ? req.query.level : user.level;
  let type = TYPES.includes(req.query.type) ? req.query.type : TYPES[Math.floor(Math.random() * TYPES.length)];

  if (user.usage.date !== today()) user.usage = { date: today(), count: 0 };
  if (!isPremium(user) && user.usage.count >= config.freeDailyLimit) {
    return res.status(402).json({ error: 'limit', message: 'Дневной лимит бесплатных упражнений исчерпан. Оформите Premium!' });
  }

  const pool = (db.pool[level] && db.pool[level][type]) || [];
  const recent = new Set(user.recent || []);
  let exercise, source;
  // Prefer a pool exercise the user hasn't seen yet.
  let idx = pool.findIndex(ex => !recent.has(exHash(ex)));
  if (idx === -1 && pool.length > 0) idx = 0;
  if (idx !== -1) {
    exercise = pool.splice(idx, 1)[0];
    source = 'ai';
  } else {
    const fb = FALLBACK[type];
    const fresh = fb.filter(ex => !recent.has(exHash(ex)));
    exercise = (fresh.length ? fresh : fb)[Math.floor(Math.random() * (fresh.length ? fresh.length : fb.length))];
    source = 'builtin';
  }
  // Refill in the background when the pool runs low.
  if (pool.length < 4) refillPool(level, type);

  rememberServed(user, exHash(exercise));
  user.usage.count++;
  saveDb();
  res.json({ exercise, source, level, usedToday: user.usage.count, dailyLimit: config.freeDailyLimit, premium: isPremium(user) });
});

app.post('/api/result', auth, (req, res) => {
  const { correct } = req.body || {};
  const user = req.user;
  user.done++;
  if (correct) { user.correct++; user.xp += 10; } else { user.xp += 2; }
  const t = today();
  if (user.lastActiveDay !== t) {
    const yesterday = new Date(Date.now() - 24 * 3600 * 1000).toISOString().slice(0, 10);
    user.streak = user.lastActiveDay === yesterday ? user.streak + 1 : 1;
    user.lastActiveDay = t;
  }
  saveDb();
  res.json({ user: publicUser(user) });
});

// AI free-form answer check (e.g. translations) — uses Claude via subscription.
app.post('/api/ai/check', auth, async (req, res) => {
  const { ru, expected, answer } = req.body || {};
  if (!ru || !answer) return res.status(400).json({ error: 'Нет данных' });
  const user = req.user;
  if (user.usage.date !== today()) user.usage = { date: today(), count: 0 };
  if (!isPremium(user) && user.usage.count >= config.freeDailyLimit) {
    return res.status(402).json({ error: 'limit', message: 'Дневной лимит исчерпан. Оформите Premium!' });
  }
  try {
    const raw = await callAI(
      `A Russian-speaking student translated the sentence "${String(ru).slice(0, 300)}" into English as: "${String(answer).slice(0, 300)}".
Reference translation: "${String(expected || '').slice(0, 300)}".
Judge if the student's translation is acceptable (correct grammar and meaning; minor stylistic differences are OK).
Return ONLY a JSON array with one object: [{"ok":true|false,"comment":"<1-2 sentence feedback in Russian, mention the mistake if any>"}]`,
      90000
    );
    const [verdict] = extractJson(raw);
    res.json({ ok: !!verdict.ok, comment: String(verdict.comment || '') });
  } catch (e) {
    res.status(500).json({ error: 'ИИ-проверка недоступна: ' + e.message });
  }
});

// --- Subscription ---
app.post('/api/subscription/check', auth, async (req, res) => {
  const result = await daPollDonations();
  res.json({ ...result, user: publicUser(req.user) });
});

// One-time DonationAlerts OAuth connection (admin only).
app.get('/api/da/connect', (req, res) => {
  const user = parseSession(req.headers.cookie);
  if (!user || !isAdmin(user)) return res.status(403).send('Только для администратора');
  if (!config.daClientId) return res.status(400).send('daClientId не указан в config.json');
  const url = DA_BASE + '/oauth/authorize?' + new URLSearchParams({
    client_id: config.daClientId,
    redirect_uri: config.daRedirectUri,
    response_type: 'code',
    scope: 'oauth-user-show oauth-donation-index'
  });
  res.redirect(url);
});

app.get('/api/da/callback', async (req, res) => {
  const code = req.query.code;
  if (!code) return res.status(400).send('Нет кода авторизации');
  try {
    const r = await fetch(DA_BASE + '/oauth/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: config.daClientId,
        client_secret: config.daClientSecret,
        redirect_uri: config.daRedirectUri,
        code
      })
    });
    const data = await r.json();
    if (!data.access_token) return res.status(500).send('DA не вернул токен: ' + JSON.stringify(data));
    db.daTokens = {
      access: data.access_token,
      refresh: data.refresh_token || null,
      expiresAt: Date.now() + (data.expires_in || 3600) * 1000
    };
    saveDb();
    res.send('DonationAlerts подключен! Можно закрыть вкладку.');
  } catch (e) {
    res.status(500).send('Ошибка: ' + e.message);
  }
});

// Manual premium grant (admin).
app.post('/api/admin/grant', auth, (req, res) => {
  if (!isAdmin(req.user)) return res.status(403).json({ error: 'Только для администратора' });
  const { email, days } = req.body || {};
  const target = Object.values(db.users).find(u => u.email === email);
  if (!target) return res.status(404).json({ error: 'Пользователь не найден' });
  const base = Math.max(target.premiumUntil, Date.now());
  target.premiumUntil = base + (Number(days) || config.premiumDays) * 24 * 3600 * 1000;
  saveDb();
  res.json({ ok: true, premiumUntil: target.premiumUntil });
});

app.listen(config.port, () => {
  console.log(`Englify running at http://localhost:${config.port}`);
  console.log(`AI provider: ${config.aiProvider}`);
  console.log(`Google login: ${config.googleClientId ? 'configured' : 'NOT configured (dev login enabled)'}`);
  console.log(`DonationAlerts: ${db.daTokens ? 'connected' : (config.daClientId ? 'configured, visit /api/da/connect' : 'not configured')}`);
});
